package com.permission.processor.util;

/**
 * create date:  2018/8/1
 * creator:  luoyonghui
 * functional description:
 */
public class Constants {
    public static final String DEPRECATED_MESSAGE = "android.app.Fragment was deprecated in Android P.";
    public static final String FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!";
    public static final String GEN_CLASS_SUFFIX = "_PermissionsDispatcher";
    public static final String GEN_REQUEST_CODE_PREFIX = "REQUEST_";
    public static final String GEN_PERMISSION_PREFIX = "PERMISSION_";
    public static final String GEN_PENDING_PREFIX = "PENDING_";
    public static final String GEN_WITH_PERMISSION_CHECK_SUFFIX = "WithPermissionCheck";
    public static final String GEN_PERMISSION_REQUEST_SUFFIX = "PermissionRequest";
}
